# Activate with: MICRONAUT_ENVIRONMENTS=docker
datasources.default.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:room_db}
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.username=${DB_USER:root}
datasources.default.password=${DB_PASSWORD:root}
datasources.default.dialect=MYSQL
datasources.default.initialization-fail-timeout=60000
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true
jpa.default.entity-scan.packages=com.motel.domain
